trigger:
  - main

pool:
  name: Default  # ✅ Uses your own self-hosted agent

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  - script: |
      cd my-app
      npm install
      npm run build
    displayName: 'Build React App'

  - script: |
      cd shopping-backend
      npm install
      npm start
    displayName: 'Start Backend Server'
